<h1>Python: without numpy or sklearn </h1>

<p style = "background : pink"> Importing libraries

In [1]:
import numpy as np
import pandas as pd

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A=np.array([[2,3],[3,4]])
B=np.array([[1,2],[3,4]])
(A1,A2)=A.shape
(B1,B2)=B.shape

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    (A1,A2)=A.shape
    (B1,B2)=B.shape
    if A2 != B1 :
        return("Not possible")
    else:
        C = np.dot(A,B)
        return(C)
matrix_mul(A, B)

array([[11, 16],
       [15, 22]])

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [3]:
from random import uniform
import random
from bisect import bisect                                # this module taken from  geekfromgeeks website
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]

# you can free to change all these codes/structure
def sampling_based_on_magnitued(A):
    totsum = 0

    for i in range(len(A)):                       # Adding up all the element in the list A
        totsum += A[i]
    prob= [A[i]/totsum for i in range(len(A))]    # Finding the probabilities of each element in A
    
    ############################### Creating cummulative sum #################################
        
    lst=[] 
    zzz=0
    for i in range(0,len(prob)):
        zzz += prob[i]
        lst.append(zzz) 
     
    print(lst)
    ################################ Cummulative sum ends ######################################
    num_random =[]
    ############################### Printing randomly selected values from the list ###########
    for i in range(100):
            i = random.uniform(0.0,1.0)          # selecting a random number from  0 to 1           
            p = bisect(lst, i)                   # selecting corresponding indexed value from list 
            num_random.append(A[p])              # appending 100 times
    return num_random

sampling_based_on_magnitued(A)

[0.0, 0.01597444089456869, 0.10223642172523961, 0.12140575079872204, 0.16293929712460065, 0.2523961661341853, 0.5718849840255591, 0.7156549520766773, 0.7476038338658146, 1.0]


[28,
 79,
 100,
 100,
 79,
 100,
 6,
 79,
 6,
 79,
 79,
 100,
 28,
 45,
 45,
 100,
 5,
 28,
 100,
 6,
 28,
 100,
 79,
 27,
 45,
 28,
 45,
 10,
 100,
 79,
 100,
 79,
 45,
 79,
 100,
 27,
 79,
 28,
 100,
 28,
 79,
 79,
 28,
 100,
 28,
 100,
 27,
 45,
 10,
 79,
 79,
 5,
 100,
 45,
 79,
 79,
 100,
 100,
 45,
 28,
 45,
 45,
 100,
 100,
 100,
 45,
 79,
 13,
 79,
 45,
 79,
 79,
 45,
 45,
 79,
 28,
 27,
 45,
 27,
 5,
 45,
 45,
 100,
 100,
 100,
 79,
 100,
 100,
 27,
 79,
 27,
 100,
 45,
 100,
 79,
 79,
 27,
 79,
 79,
 100]

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [4]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):                            # https://www.geeksforgeeks.org/python-replace-all-numbers-by-k-in-given-string/
    String = re.sub("[^0-9]","",str(String))           # https://docs.python.org/3/library/re.html
    String = re.sub('\d','#',String)
    return String # modified string which is after replacing the # with digits

# print(replace_digits(['234','a2b3c4','abc','#2a$#b%c%561#'])) # not working why?
print(replace_digits('a2b3c4'))
print(replace_digits('234'))
print(replace_digits('#2a$#b%c%561#'))
print(replace_digits('abc'))

###
###
####



<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [5]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

table_of_marks = pd.DataFrame({'Students': Students,"Marks" : Marks})

def display_dash_board(students, marks):
    
    table_sorted = table_of_marks.sort_values("Marks", ascending = False)  # sorting by marks in descending order
       
    top_5_students = table_sorted.head()     # code for computing top least 5 students
    
    least_5_students = table_sorted.tail()   # code for computing top least 5 students
    
    
    Q1 = table_of_marks["Marks"].quantile(0.25)
    Q3 = table_of_marks["Marks"].quantile(0.75)
    IQR = table_of_marks[(table_of_marks["Marks"] >= Q1) & (table_of_marks["Marks"] <= Q3)]
    
    # write code for computing top least 5 students
    students_within_25_and_75 = IQR
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print(top_5_students, least_5_students, students_within_25_and_75)

    Students  Marks
7   student8     98
9  student10     80
1   student2     78
4   student5     48
6   student7     47    Students  Marks
0  student1     45
5  student6     43
8  student9     35
3  student4     14
2  student3     12    Students  Marks
0  student1     45
4  student5     48
5  student6     43
6  student7     47


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [6]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
        
    cosine_distance = []
    for a,b in S:
        numerator = (P[0]*a + P[1]*b)
        denominator = ((P[0]**2 + P[1]**2) * (a**2 + b**2))**0.5
        cosine_distance.append(math.acos(numerator/denominator))

    table_dist = pd.DataFrame({"S":S, "cosine_distance": cosine_distance})  # creating a dataframe so that sorting is easy
    sorted_table = table_dist.sort_values("cosine_distance")                # by default the order is ascending
    closest_points_to_p = sorted_table["S"].head()
    print(sorted_table["S"].head())                                         # printing only the points which are close to P
    return closest_points_to_p  # its list of tuples

S = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P = (3,-4)
points = closest_points_to_p(S, P)
print() #print the returned values

3     (6, -7)
8     (1, -1)
7      (6, 0)
5    (-5, -8)
6    (-1, -1)
Name: S, dtype: object



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [26]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print() # the returned value

In [29]:
def dist(a,b):
    
    # This function returns distance (here defined as 'sum') between line and the point (a,b)
    # If sum = 0 this means point lies on the line. If sum != 0 this means points lies on one of the sides of line
                                
    sum = 0
    
    # Since I dont know how to retreive + and - symbols as operatores I am trying all 4 possible cases of expression
    
    if S[2] == '+' and S[5] == '+' :  
        sum = a*coeff_x + b*coeff_y + intercept     # distance between a point and a plane
    
    if S[2] == '+' and S[5] == '-' :  
        sum = a*coeff_x + b*coeff_y - intercept 
    
    if S[2] == '-' and S[5] == '+' :   
        sum = a*coeff_x - b*coeff_y + intercept 
    
    if S[2] == '-' and S[5] == '-' : 
        sum = a*coeff_x - b*coeff_y - intercept 

    return sum

def sign():
    sign_red = []
    sign_Blue = []

    for a,b in Red:
        sign_red.append(dist(a,b))
    print(sign_red)

    sign_blue = []
    for a,b in Blue:
        sign_blue.append(dist(a,b))
    print(sign_blue)
    
    # ========================== finding on which side of the lines the points are ======================
    
    z = 0
    for i in range(len(sign_red)):
        if sign_red[i] >= 0:
            z += 1
    y = 0
    for i in range(len(sign_blue)):
        if sign_blue[i] >= 0:
            y += 1    
    
    # ================= of all points how many points are having same sign (+ or -) ======================
    print(z)   
    print(y)    
    
        
    # ===============Conforming whether a point lies on same side on the two lines or not ================
    
    if (z == len(sign_red)) & (y == 0) or (z == 0) & (y == len(sign_blue)): 
        print("YES")
    else:
        print("NO")
    
print(sign)

<function sign at 0x00000241E3237C18>


In [31]:
for i in range(len(Lines)):
    S = list(Lines[i])
    a,b = Red[0]
    
    # ========================== getting coefficients of given expressions =============================
    coeff_x = int(S[0])                  
    coeff_y = int(S[3])
    intercept = int(S[6])
    
    sign()

[2, 3, 6, 6, 3]
[-3, -3, -5, -4, -2]
5
0
YES
[0, 1, 2, -2, -5]
[-1, 1, -1, -2, 4]
3
2
NO
[-2, -1, 1, -1, -4]
[-5, -4, -6, -6, -2]
1
0
NO
[1, 1, 2, 4, 4]
[-1, -2, -2, -1, -3]
5
0
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [32]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

SyntaxError: unexpected EOF while parsing (<ipython-input-32-73f1a494dfa4>, line 13)

In [33]:
S=  "_,_,30,_,_,_,50,_,_"        # converting S to a list
lst = S.split(",")

k = 0
l = 0
m = 0
zz= 0

new_lst =[]

final_lst = []
new_lst2 = []
for i in lst:
    l += 1
    if i != '_':
        new_lst.append(int(i))
        new_lst2.append(l)
        k = int(i)
        m += 1
        
        if m==1 :
            for a in range(l):
                 lst[a] = k/l
        else:          
            zz = int(lst[l-1])+int(lst[new_lst2[m-2]-1])
            for x in range(new_lst2[m-2],new_lst2[m-1]+1):
                lst[x-1] = zz/(new_lst2[m-1]-new_lst2[m-2]+1)
    
    if (i == '_') & (l == len(lst)) :
        for y in range(new_lst2[m-1],l+1):
            lst[y-1] = int(lst[new_lst2[m-2]])/(l+1 - new_lst2[m-1])
print(lst)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [34]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

    A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

In [35]:
def prob(x,y):
    N = 0
    D = 0
    prob = 0
    for a,b in A:
        if (a==x) & (b==y):
            N += 1
        if b == y:
            D += 1
    
    return (N/D)

lst_prob =[]
for i in A:
    a = i[0]
    b = i[1]
    probability = prob(i[0],i[1])
    lst_prob.append(probability)
    print("P(F={} | S ={}) = {}".format(a,b,probability))

TypeError: 'int' object is not subscriptable

## <h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [36]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S1_set = set(S1.split(" "))
    S2_set = set(S2.split(" "))

    Common_words = S1_set.intersection(S2_set)
    Words_in_S1_not_S2 = S1_set.difference(S2_set)
    Words_in_S2_not_S1 = S2_set.difference(S1_set)
    a = Common_words
    b = Words_in_S1_not_S2
    c = Words_in_S2_not_S1
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

{'column', 'contain', 'only', 'will', 'the', 'uniques', 'values'} {'first', 'F', '5'} {'second', 'S', '3'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [37]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    sum = 0
    for a, b in A:
        
        sum += a*math.log(b)
        loss = -sum/len(A)
        
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.4434224864800296


# End